import Header from '@/components/Header';
import './globals.css';
import type { Metadata } from 'next';
import { Poppins, Raleway } from 'next/font/google';
import Footer from '@/components/Footer';

const poppins = Poppins({
    subsets: ['latin'],
    style: 'normal',
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
    variable: '--font-poppins',
    display: 'swap',
    adjustFontFallback: false,
    preload: false,
});

const raleway = Raleway({
    subsets: ['latin'],
    style: 'normal',
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
    variable: '--font-raleway',
    display: 'swap',
    adjustFontFallback: false,
    preload: false,
});

export const metadata: Metadata = {
    title: 'Rambbble',
    description: 'Generated by create next app',
    authors: [{ name: 'Oluwatowo Rosanwo', url: 'crim-son.space' }],
    applicationName: 'Rambbble',
    creator: 'Oluwatwo Rosanwo',
    generator: 'Next.js',
    keywords: ['travel', 'social', 'people', 'connect', 'planes', 'meet'],
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={[poppins.variable, raleway.variable].join(' ')}>
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
